    CREATE TABLE KATEGORI(
    KODE_KAT VARCHAR(255) PRIMARY KEY,
    NAMA_KAT VARCHAR(255) NOT NULL
);

CREATE TABLE USER(
    FNAME VARCHAR(255) NOT NULL,
    LNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) PRIMARY KEY,
    NOTELP VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    LEVEL VARCHAR(255) NOT NULL,
    STATUS INT NOT NULL,
    SALDO NUMERIC(9)
);

CREATE TABLE BARANG(
    ID int(30) PRIMARY KEY AUTO_INCREMENT,
    NAMA_BARANG VARCHAR(255) NOT NULL,
    MERK VARCHAR(255) REFERENCES MERK(KODE_MERK),
    KATEGORI VARCHAR(255) REFERENCES KATEGORI(KODE_KAT),
    STOK NUMERIC(30),
    HARGA NUMERIC(30) NOT NULL
);